version: '3.1'

services:

  gocd-server:
    image: gocd/gocd-server:v17.5.0
    ports:
      - 8153:8153
      - 8154:8154
    volumes:
      - /mnt/data/go/godata:/godata
      - /mnt/data/go/home-dir:/home/go
    networks:
      default:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    secrets:
      - source: ca.pem
        target: ca.pem
      - source: cert.pem
        target: cert.pem
      - source: key.pem
        target: key.pem

  gocd-agent01:
    image: quay.io/feedyard/baseline-gocd-agent:3.5.25
    environment:
      GO_SERVER: gocd-server
      AGENT_AUTO_REGISTER_KEY: e5c56276-be00-47f2-8bfc-92bef98e9f60
      AGENT_AUTO_REGISTER_HOSTNAME: baseline-gocd-agent01
    volumes:
      - /mnt/data/go/godata:/godata
      - /mnt/data/go/home-dir:/home/go
    networks:
      default:
    depends_on:
      - gocd-server
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3

networks:
  default:
