version: 2

jobs:
  build:
    working_directory: ~/baseline_gocd
    environment:
      LIBRARY: feedyard
      CONTAINER_NAME: baseline-gocd
      VERSION: 17.5
      BASH_ENV: .circlerc
    docker:
      - image: feedyard/circleci-docker:3.6.36
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: 'docker info'
      - run:
          name: decrypt ca.pem
          command: 'openssl aes-256-cbc -d -in ca.ci -out ca.pem -k $KEY'
      - run:
          name: decrypt cert.pem
          command: 'openssl aes-256-cbc -d -in cert.ci -out cert.pem -k $KEY'
      - run:
          name: decrypt key.pem
          command: 'openssl aes-256-cbc -d -in key.ci -out key.pem -k $KEY'
      - run:
          name: decrypt secrets
          command: 'openssl aes-256-cbc -d -in secrets.ci -out .circlerc -k $KEY'
      - run:
          name: build-gocd-server
          command: 'docker-compose build gocd-server'
      - deploy:
          command: 'docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=$SWARM_HOST:2376 stack deploy --compose-file docker-compose.yml baseline'
