version: 2
jobs:
  build:
    working_directory: ./
    docker:
      - image: circleci/python:3.6
    steps:
          - checkout
          - setup_remote_docker
          - run: |
            docker info
            docker-compose build baseline-gocd-server