version: 2
jobs:
  build:
    working_directory: ~/baseline_gocd
    docker:
      - image: circleci/python:3.6
    steps:
          - checkout
          - setup_remote_docker
          - run:
              name: confirm Docker
              command: 'docker info'
          - run:
              name: build-gocd-server
              command: 'docker-compose build baseline-gocd-server'